# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/BirdSong',
                'doc_host': 'https://exiomius.github.io',
                'git_url': 'https://github.com/exiomius/BirdSong',
                'lib_path': 'BirdSong'},
  'syms': {'BirdSong.core': {'BirdSong.core.foo': ('core.html#foo', 'BirdSong/core.py')}}}